[build]
  environment = { NODE_ENV = "production" }
  command = "npm run build"
  publish = "build/"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from = "/a-good-internet-citizen"
  to = "/feed.xml"
