[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from = "/feeding"
  to = "/feed.xml"
  status = 301
